// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rgp.TvSeries.Data.V1.Db;

#nullable disable

namespace Rgp.TvSeries.API.Migrations
{
    [DbContext(typeof(TvSeriesDbContext))]
    partial class TvSeriesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Rgp.TvSeries.Core.Entities.TvSeries", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TvSeries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c74503d1-b354-4483-97df-a071b24c320a",
                            Summary = "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
                            Title = "Breaking Bad"
                        },
                        new
                        {
                            Id = "17a9efe3-1b70-48dc-af3a-55615f54bca6",
                            Summary = "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
                            Title = "Stranger Things"
                        },
                        new
                        {
                            Id = "082c5128-33a0-4373-8eda-ecb329947fa6",
                            Summary = "The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.",
                            Title = "Lost"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
