// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rgp.TvSeries.Data.V1.Db;

#nullable disable

namespace Rgp.TvSeries.Data.Migrations
{
    [DbContext(typeof(TvSeriesDbContext))]
    partial class TvSeriesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Rgp.TvSeries.Core.Entities.TvSeries", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TvSeries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d641c48b-eea7-4a5e-900f-3f8677dd76f9",
                            Summary = "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
                            Title = "Breaking Bad"
                        },
                        new
                        {
                            Id = "b359f834-4a89-4d21-be97-fe6577708472",
                            Summary = "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
                            Title = "Stranger Things"
                        },
                        new
                        {
                            Id = "5c095b53-8c7d-4d22-9ecc-65f3a50ac216",
                            Summary = "The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.",
                            Title = "Lost"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
